title: Databricks Apps Adoption Playbook
description: Field vs Product framework for driving adoption
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: ""
url: "https://playbook.avianna.ai"

# Enable markdown inside HTML blocks
markdown: kramdown
kramdown:
  parse_block_html: true

